### ISSUE TITLE
Name of the application

### ISSUE THREAD

**Issue by probonopd** [tunepack/tunepack-desktop#6]
Why is the application called "Tunepack" for the Mac and "tunepack-desktop" for the Linux AppImage?  Is this related to https://github.com/electron-userland/electron-builder/issues/1895? I noticed that many Electron-based AppImages have "nice" filenames for the Mac but less beautiful, lower-case filenames for the AppImage. 

`Tunepack-1.0.6-x86_64.AppImage` would be preferred.

<img width="341" alt="" src="https://user-images.githubusercontent.com/2480569/58532093-c2120c00-81e4-11e9-8480-90ca1d45991e.png">

**Comment by team-tunepack** [comment]
Feel free to open a PR, seems low priority for now.

**Comment by probonopd** [comment]
Apparently electron-builder is still not using not using `productName` which I had hoped was fixed long time ago:

https://github.com/tunepack/tunepack-desktop/blob/6d4982f1368b1567a24a944dc4a2b220f8a1e2be/package.json#L2-L3

So this seems to be an issue in electron-builder, not this project.

Reference:
https://github.com/electron-userland/electron-builder/issues/1895
